### ISSUE TITLE
Telldus climate sensor

### ISSUE THREAD

**Issue by fresim** [yhaugom/com.telldus#11]
Hi.
Any plan to add Telldus Climate Sensor 313159?

Br F

**Comment by xeterixon** [comment]
It already supported, but not by this app.
You can use [https://apps.athom.com/app/com.weather-sensors](https://apps.athom.com/app/com.weather-sensors)
I did have som trouble using the app from the app-store, so I took the code from the repo [https://github.com/nlrb/com.weather-sensors](https://github.com/nlrb/com.weather-sensors)

**Comment by fresim** [comment]
downloaded dev version of Wireless Weather Sensors. fixed!
