### ISSUE TITLE
Plug-in Switch (Schuko) flows work randomly

### ISSUE THREAD

**Issue by Paronfesken** [yhaugom/com.telldus#13]
Plug-in Switch (Schuko) flows seams to work from time to time.

**Comment by yhaugom** [comment]
Does not make sense that this should be due to problems in this app as far as I can understand. Guess it must be a more fundamental error in the (Athom) system?! But I will try to make time to have a look at the code. I am really busy these days.

**Comment by Paronfesken** [comment]
I'm trying an advice I read that I should set the timer for 1 second. I'll report back! Works manually tho. I'm ordering a button to try in flows and to see if this works.

**Comment by UglyDuckling2k** [comment]
Any updates? 

I'm also having problems with my switches (Telldus PLUGIN RECEIVER MINI Z-WAVE). Randomly they don't work, especially if you try to turn them all off/on at the same time.

After talking to the support at Athom they finally directed me here.

Looking at the debug information under z-wave in the developer tools I can see that I have some tx errors. The ranges between the recievers and homey are between 2-3 meters.

**Comment by yhaugom** [comment]
Have made some changes in the code to make I compatible with new validator. A got it validating, and it is on GitHub, but I was stupid enough to update npm, and that broke my nose/npm setup. So I cannot longer run athom-cli to install locally. Need to fix that first. 
I made some changes to id's in the app.json file, so I am little worried it can break something like flows or devices?! Didn't check how Athom handles this yet. So I would like to test it before I publish to the  Athom App Store. If someone wants to give it a try, feel free, but on your own risk.

**Comment by yhaugom** [comment]
Tested it on my setup last night, nothing broke for me. But I only have two magnetic door/window switches myself. 
Settings seem to work better on the magnet switch now.

**Comment by yhaugom** [comment]
@UglyDuckling2k What have you tried with Athom support? Did you try to heal the node under developer tools and Z-wave?
If you paired the device close to Homey and then moved it far away, it might need to use mesh to get in touch with Homey. Could this be the reason?
Are you able to supply me with some logs of the transfer errors? Enable logging and filter on one device with this problem.

**Comment by yhaugom** [comment]
I would guess this is the same reason as the status is not updating. Since the status is not updating the flow is not fired either. I will prioritize finding out why status does not update.

**Comment by yhaugom** [comment]
Think this has to do with Athom core functions. I am not doing anything special as I know in the app at the moment. Without more information I cannot test more. I would need some diagnostics reports, and the corresponding id, and some more information, since I dont own the plugs myself.

I will close the issue for now. Feel free to comment or reopen the issue if you have some more information.
