### ISSUE TITLE
Device status after power failure is wrong i advanced settings

### ISSUE THREAD

**Issue by marcus-karlsson** [yhaugom/com.telldus#16]
Under advanced settings "Setting device status after power failure" the legend is wrong Plug-in Switch mini (TZWP-102).

It reads:
0 = Always off (default)
1 = Remember Status
2 = Always on.

0 (zero) is actually equal to remember status, 1= Always on and 2 = Always off.
I have tested this on several plugs with firmware version 771. 
Please correct this as it can be confusing and lead one to belive the plug-in switch is defective.

Thanks
Marcus

**Comment by yhaugom** [comment]
Thank you for reporting this. Sorry for the inconvenience. Will be fixed in next version. I don't own the plugs myself, and didn't check the documentation well enough apparently.

**Comment by marcus-karlsson** [comment]
Thank You very much for quick response and quick action!
