### ISSUE TITLE
Plug-in Switch Mini Default Advanced settings for meter report are too aggressive 

### ISSUE THREAD

**Issue by marcus-karlsson** [yhaugom/com.telldus#17]
When adding a Plug-in Switch Mini type TZWP-102 the time settings for meter reports are too agressive.
They are set to value "5" which means 5 seconds. With many of these plugs it means 4 metrics per plug every 5 seconds has to be sent over the mesh to Homey. 
I recommend in next release setting defaults values to the default settings documented by Telldus.
600 second for power (W)
3600 seconds for Energy (kWh)
0 (disabled) for voltage (V) and current (A). These are anyhow not seen in Homey insights.

Below is cut and past from attached technical manual.
My feeling is not getting updates for these values in Homey can in part be caused by to excessive reporting set in the plugs. 
[TELLDUS_TZWP-102_technical-manual.pdf](https://github.com/yhaugom/com.telldus/files/2884860/TELLDUS_TZWP-102_technical-manual.pdf)

Parameter no 101 - Power (W) report interval
This parameter defines the period of sending power reports
Default value: 600 seconds
Size: 4 byte
Possible values: 0: Disabled, 5-2678400 seconds
Parameter no 102 - Energy (kWh) report interval
This parameter defines the period of sending energy reports
Default value: 3600 seconds
Size: 4 byte
Possible values: 0: Disabled, 5-2678400 seconds
Parameter no 103 - Voltage (V) report interval
This parameter defines the period of sending voltage reports
Default value: 0 (Disabled)
Size: 4 byte
Possible values: 0: Disabled, 5-2678400 seconds
Parameter no 104 - Current (A) report interval
This parameter defines the period of sending current reports
Default value: 0 (Disabled)
Size: 4 byte
Possible values: 0: Disabled, 5-2678400 seconds

Regards
Marcus

**Comment by yhaugom** [comment]
I guess you are right. I now see some more issues with the settings for this device. I got this part of the code from another developer, and didn't test it myself since I don't have the plugs. And my review of the settings has not been good enough. I tried to check it against the z-wave configuration specifications found [here](https://products.z-wavealliance.org/products/2892/configs), but I can see I did some errors from that as well.
This may explain some of the issues experienced. I will have a look soon!

**Comment by marcus-karlsson** [comment]
Thanks for looking into it. wanted to hurry up and get this to you since it seem you are working on a new release. Let me know if you need help testing. Not sure how to get test app onto homey though.

**Comment by yhaugom** [comment]
Think I should have this covered. Included in next release.

**Comment by yhaugom** [comment]
@marcus-karlsson thank you for reporting! You could clone this repo and install it on your homey locally, or I can submit this app as a beta. I think I will do that. I would appreciate feedback on the new version indeed! 
Especially the things you mentioned, and if you could have a closer look at parameter 17 - "The value here represents minimum change in wattage percent (in terms of percentage) for a meter report (watt) to be sent". In the manual it says 0-100%, but in the specs it says -128-127. Would be nice to know if I did put the correct values in.

**Comment by marcus-karlsson** [comment]
Just clone and insalled what you have done so far and it looks good. Removed and added a plug and now the default values are in line with telldus defaults. 
Verifying the minimum change in wattage can be hard for me to test as I still have issues that the plugs often do not update values as they should even when configured correctly.
My feeling though is the correct values are 1-100 (%) as noted in the manual I attached earlier. I think in the Z-wave specification you pointed me to one have by mistake entered all the signed values that can be represented by 1 byte when using 2-complement ofr negatve numbers. So it is what can be held in a byte rather than the applicable values for the parameter. 

Attaching some pics for reference. 
![screenshot_20190221-190734_homey](https://user-images.githubusercontent.com/47646332/53192675-5a5d8b00-360f-11e9-9408-ddb5d2f7d3d4.jpg)
![screenshot_20190221-190740_homey](https://user-images.githubusercontent.com/47646332/53192677-5a5d8b00-360f-11e9-987d-6bf9e5c1c7b3.jpg)
![screenshot_20190221-190748_homey](https://user-images.githubusercontent.com/47646332/53192679-5a5d8b00-360f-11e9-8134-5d5f9c9013c6.jpg)
![screenshot_20190221-190718_homey](https://user-images.githubusercontent.com/47646332/53192680-5a5d8b00-360f-11e9-85e8-895cb40b63ec.jpg)
![screenshot_20190221-190721_homey](https://user-images.githubusercontent.com/47646332/53192681-5af62180-360f-11e9-9eb1-b2b6965ff1eb.jpg)
![screenshot_20190221-190727_homey](https://user-images.githubusercontent.com/47646332/53192682-5af62180-360f-11e9-8b3f-ec7e266ee3a3.jpg)

Thanks Again!

**Comment by yhaugom** [comment]
@marcus-karlsson Thank you very much fort the feedback! 
Very helpful to see how it looks. I think it would be great to shorten the description titles as well, and just keep the longer hints. Would look much cleaner.
I did receive some user-initiated diagnostic reports, but don't know from whom.
In some of the reports it is some request_timeouts and TRANSMIT_COMPLETE_NO_ACK, but hard to see why, since it comes from the HomeyClient.

**Comment by marcus-karlsson** [comment]
Since this issue is closed I will open a new one for GUI enhancements.

Let me know if I should open one for missing meter data or if that sits with athom team. In the Z.wave tools log window I do not see any meter reports coming in for the ones that does not update so it is either an issue with the plugs(or their configuration) or something with the zwave implementatin from homey. Or at least that is what I think.

**Comment by yhaugom** [comment]
If you get no reports, then I might think it is the plug not sending any. So this is still the issue after you installed the changes manually and added the plug again? This is starting to "annoy" me so much I am thinking of buying a plug just to find out... 😄

**Comment by marcus-karlsson** [comment]
Have not seen the issue yet on the plug that was re-paired after updating the app. 
If you think re-paring all my plugs will solve the issue on the rest, I will try that on them few at a time.
I had already manually edited the report time settings on them was something else changed in the app as well that might affect meter reporting? I am very greatful for all help having spent some thousands of SEK on this type of plug.

**Comment by yhaugom** [comment]
I didn't change anything else than the default values and some of the min/max values for the parameters. But it might be some other bad default values you forgot to change? I am not sure actually. You could try a few and see if it helped maybe.
