### ISSUE TITLE
Icon missing in app for Plug-in Switch Mini (TZWP-102)

### ISSUE THREAD

**Issue by marcus-karlsson** [yhaugom/com.telldus#18]
The icon is not visible for Plug-in Switch Mini (TSWP-102).
Not in pairing GUI and not in buttons once paired. See attached screenshots. I do not know how to fix it. 

IReplaced icon.svg (com.telldus\drivers\TZWP-102\assets\icon.svg) with the icon.svg for Schuko plug (com.telldus\drivers\TZWP-100\assets\icon.svg) then that icon is visible but it is of course the wrong icon. 

Tried editing/creating new icon in incscape and re-save it. Then again there is no icon visible.
Do the svg files need to be approved/signed by Athom or do you have to make them in specific editor?

**Comment by marcus-karlsson** [comment]
Forgot the screenshots....

![screenshot_20190222-094134_homey](https://user-images.githubusercontent.com/47646332/53232270-0a240e80-368b-11e9-8ae9-6f846b3409a3.jpg)

![screenshot_20190222-093408_homey](https://user-images.githubusercontent.com/47646332/53232274-0db79580-368b-11e9-8038-0aba53068031.jpg)

**Comment by yhaugom** [comment]
I think this has to do with the way the icon is made. I used an online free png to svg converter, and that made some blank space down and to the right of the part of the image I wanted. Didn't know how to fix this, so I raised an issue [here](https://github.com/athombv/homey-vectors-public/)

Seems there are general problems with icons atm:
[Icon issue](https://github.com/athombv/homey-vectors-public/issues/51)

**Comment by yhaugom** [comment]
The icon seems fine in my opinion. Maybe just some Athom issues?? Icon for the TZWP-100 does seem small...

**Comment by JohanBendz** [comment]
There is an ongoing Athom issue about this, the icons are good.

**Comment by marcus-karlsson** [comment]
Yes the working icon could be slightly bigger. I guess than it is some Athom issue.
I actually took the working icon (TZWP-100) edited it just by removing the two black dots which are the holes where the prongs would plugin.  that icon did not work either.
I wanted to test some more but now I cannot logon to my homey from CLI anymore, getting this:
"str.replace is not a function"
Once I figure that out I can continue playing with it...

**Comment by marcus-karlsson** [comment]
@yhaugom 
By trial and error I sized up the icon for TZWP-102 to something that works for me. Made a pull request for the new icon.svg I uploaded, check it out if you want to use it...
This is what it look like for me now:

![screenshot_20190306-223755_homey](https://user-images.githubusercontent.com/47646332/53915819-f7cdab80-4060-11e9-97d9-db16c570b3f5.jpg)

**Comment by marcus-karlsson** [comment]
@yhaugom 
As the new icon has been merged I think this issue can be closed.

Thanks 
Marcus

**Comment by marcus-karlsson** [comment]
Closing it
