### ISSUE TITLE
GUI Enhancements needed for Plug-in Switch Mini (TZWP-102)

### ISSUE THREAD

**Issue by marcus-karlsson** [yhaugom/com.telldus#19]
This is an enhancement request for advanced settings GUI on Plug-in Switch Mini (TSWP-102).
Titles for "Setting time" should be shortened so that parameter values are visible in screen. 

IE 
"Setting time for sending power report (watt)"
could be shortened as
"Power report (watt) interval (s)" 

The 12 characters saved should leave plenty of space for showing the current value without going into the setting. Also adding (s) to clarify that it is a setting in seconds.

Also in the setting screen where values are edited it should be mentioned that these are settings in seconds.  
IE 
"The interval time for sending power report (watt)"
could be edited as
"The interval time in seconds for sending power report (watt)"

Also 
"Enable/disable the configuration command"
could be edited as
"Enable/disable configuration command"

![screenshot_20190222-094341_homey](https://user-images.githubusercontent.com/47646332/53235188-8883af00-3691-11e9-8df9-ce240445cc24.jpg)
![screenshot_20190222-105332_homey](https://user-images.githubusercontent.com/47646332/53235192-8a4d7280-3691-11e9-90dd-bfb04ed4e9cd.jpg)

**Comment by yhaugom** [comment]
@marcus-karlsson just pushed some changes to the ['beta'](https://github.com/yhaugom/com.telldus/tree/beta) branch. What do you think?
Tried to shorten and rewrite the titles and changed some hints as well.
I also moved the configuration lock to the top, since that is probably needed to make changes at all? Or am I misunderstanding the meaning of this?
My thought was that it should be visible on the top.

**Comment by marcus-karlsson** [comment]
@yhaugom 
Definitely looks better, think you got all changes I would ask for in this beta.

The configuration lock will block updates of the other parameters if it is set to 1.
Basically a "write protect" so settings are not accidentally changed. 

Adding two more screenshots.

Please NOTE, in Energy (KWh) "Seconds" is misspelled as "seconsd"  

Think the issue can be closed unless you want to test something else.

![screenshot_20190222-220614_homey](https://user-images.githubusercontent.com/47646332/53271747-a3850c00-36ef-11e9-9c3d-1ae03b3b5966.jpg)

![screenshot_20190222-220629_homey](https://user-images.githubusercontent.com/47646332/53272194-e5628200-36f0-11e9-9a2f-45e0dfc1c655.jpg)

**Comment by yhaugom** [comment]
Thank you again! Very helpful! I updated and pushed it to Github, and have requested update of app to beta in Athom app "store". Closing this issue.
