### ISSUE TITLE
Plug in mini switch not reporting power consumption

### ISSUE THREAD

**Issue by ketillund** [yhaugom/com.telldus#20]
I use a plug in mini switch to measure the power consumption of a heat pump. 
After the measured energy consumption reached 99,98kWh, the plug seemed to have stopped measuring. 
Power consumption has been stuck on 307W and enery consumption on 99,98kWh for the last 8 hours, and this is clearly wrong. 
Is there a limit of 2 digits on the energy counter? 
And shouldn't there be a way to reset this counter?
I'm running version 1.1.0 of the app

**Comment by ketillund** [comment]
Update: After 10 hours of both power meter and power being stuck, the mini plug suddenly started reporting again. 
However, I still miss the possibility of resetting the power meter.

**Comment by marcus-karlsson** [comment]
@ketillund  Have you tried re-paring switch after updating to last version of the app?
Check what your report timeouts are in advanced settings, You probably want to go with something like 300seconds for watts and 1800 seconds for KWh. Voltage and Amperage you can set to 0 as they are not currently shown in insights. My experience is that the old defaults settings of 5s or something like that was way too agressive and would cause similar issues. Also check to be on latest and greatest version of Homey firmware.

**Comment by FingolSE** [comment]
I also have issues with the Z-WAVE MINI PLUG-IN SWITCH from Telldus. In my use case the switch is remote operated via homey between 1-3 times a day. The operation is flawless for 8-10 days and then the connection is broken (no remote operation, not power reporting) until the switch is power cycled and after that back to normal again for 8-10 days.

**Comment by yhaugom** [comment]
@ketillund 

> I use a plug in mini switch to measure the power consumption of a heat pump.
After the measured energy consumption reached 99,98kWh, the plug seemed to have stopped measuring.
> Power consumption has been stuck on 307W and enery consumption on 99,98kWh for the last 8 hours, and this is clearly wrong.
> Is there a limit of 2 digits on the energy counter?
This is not controlled by the app itself, the app only registers the device it's capabilities like this;
```
this.registerCapability('onoff','BASIC');
this.registerCapability('onoff','SWITCH_BINARY');
this.registerCapability('meter_power','METER');
this.registerCapability('measure_power','METER');` 
Homey meshdriver takes care of the rest. So, no, there is no 2 digit limit as far as I know.

```

> And shouldn't there be a way to reset this counter?
Again, this is nothing I can do in the app that I know of. I think this is controlled by Homey. 

> I'm running version 1.1.0 of the app

> Update: After 10 hours of both power meter and power being stuck, the mini plug suddenly started reporting again.
Check to see if the device is directly connected to Homey, or if it is "meshed" trough a lot of devices at developer.athom.com -> Tools -> Z-wave. You could also check the log and filter out the plug to see if data is recieved to Homey from it at all. 

> However, I still miss the possibility of resetting the power meter.

**Comment by yhaugom** [comment]
> also have issues with the Z-WAVE MINI PLUG-IN SWITCH from Telldus. In my use case the switch is remote operated via homey between 1-3 times a day. The operation is flawless for 8-10 days and then the connection is broken (no remote operation, not power reporting) until the switch is power cycled and after that back to normal again for 8-10 days.

Can you check to see if homey receives any information at all next time it stops working? Go to [developer.athom.com -> tools -> Z-wave](https://developer.athom.com/tools/zwave) and find your device node id in the list. Then enable logging and add a filter like 'Node[<your_device_node_id>]'. Ex. _Node[34]_

**Comment by FingolSE** [comment]
> > also have issues with the Z-WAVE MINI PLUG-IN SWITCH from Telldus. In my use case the switch is remote operated via homey between 1-3 times a day. The operation is flawless for 8-10 days and then the connection is broken (no remote operation, not power reporting) until the switch is power cycled and after that back to normal again for 8-10 days.
> 
> Can you check to see if homey receives any information at all next time it stops working? Go to [developer.athom.com -> tools -> Z-wave](https://developer.athom.com/tools/zwave) and find your device node id in the list. Then enable logging and add a filter like 'Node[<your_device_node_id>]'. Ex. _Node[34]_

Unfortunatly Athome just removed compatibility for 1.5.13 homeys in the developer interface. *sigh*

**Comment by yhaugom** [comment]
Can not see anything I can do with this. Hope the problem is solved. Please let me know it it doesn't work on v5 (SDK 3) and last version.
