### ISSUE TITLE
This is because Athom changed the way a device is included. They first do a removal before including the device to make sure it is completely removed.

### ISSUE THREAD

**Issue by BolmsoAnders** [yhaugom/com.telldus#27]
This is because Athom changed the way a device is included. They first do a removal before including the device to make sure it is completely removed. 
I think it is due to the problem that occurs when a device including partially fails. Then you previously had to remove the device manually before re-including.
I will try to find a more generic description, but this description is actually not incorrect... technically.

_Originally posted by @yhaugom in https://github.com/yhaugom/com.telldus/issues/26#issuecomment-744721419_

**Comment by yhaugom** [comment]
Updated the instructions.
