### ISSUE TITLE
Unable to add Telldus door sensor

### ISSUE THREAD

**Issue by yodalainen** [yhaugom/com.telldus#36]
Hi! 

I'm unable to add the Telldus door sensor to my Athom homey pro. I can pair the device but it does not recognise it as a Telldus door sensor and just adds a Basic Z-wave device. 

From the manual I cannot see anywhere how to factory reset the sensor but I have tried holding the button down for a long while and that seems to have initiated something. Link to the manual telld.us/m15110.

Is it required to have a Tellstick to include the sensor to Homey or can you do it directly?

When I look at the settings i get this Device info:
Z-Wave Device Information
Secure
⨯
Battery
✓
Device ID
35
Manufacturer ID
520
Product Type ID
512
Product ID
8
Firmware Version
1
Firmware Sub Version
5
Firmware ID
2048
Hardware Version
2
Device Class (Basic)
BASIC_TYPE_ROUTING_SLAVE
Device Class (Generic)
GENERIC_TYPE_SENSOR_NOTIFICATION
Device Class (Specific)
SPECIFIC_TYPE_NOTIFICATION_SENSOR

**Comment by maral046** [comment]
I have exactly the same problem independent of how far away I am from the controller during pairing.
![66333AF4-21A0-4D27-ACD1-E20D18F79E3A](https://user-images.githubusercontent.com/91084866/134044381-15756b52-3e05-4fdc-a5cc-db0c2ba280d5.jpeg)

**Comment by yhaugom** [comment]
This door sensor is not currently supported in the app. Needs to be added first to work. I do not have much time in the nearest future for this unfortunately.

Maybe it will work to just add the IDs for now, but it might not support everything.

I will try to have a quick look this weekend, but it will then be a quick-fix, and only BETA if anything.

**Comment by maral046** [comment]
Thanks a lot for your swift reply. I found out that Hank have support for it in their app so no stress.

**Comment by yhaugom** [comment]
Actually, it looks like this device is not really a Telldus device, but a "rebranded" device. Found several different versions.
https://products.z-wavealliance.org/products/2968
https://products.z-wavealliance.org/products/1896
https://products.z-wavealliance.org/products/2148
https://products.z-wavealliance.org/products/2958
Couple of them for American market. And found a "no-brand" version as well...

But I will try to add it later.

**Comment by yhaugom** [comment]
No immediate plan to add it. I have a lot on my plate. But later, when I have some time I might. Se other comments above for a way to use the device for now.

**Comment by yhaugom** [comment]
Added device. Currently in beta/test.
[https://homey.app/no-no/app/com.telldus/Telldus-Z-wave/test/](https://homey.app/no-no/app/com.telldus/Telldus-Z-wave/test/)
