### ISSUE TITLE
Unable to add Telldus TZWP-102/313510

### ISSUE THREAD

**Issue by Ellwiz** [yhaugom/com.telldus#39]
Hello,
Want to leave my Animus Heart and just got my Homey Pro and started with connected a Telldus 433mhz plug without any problems.
When I´m trying add a Telldus Z-wave Miniplug TZWP-102/313510, pairing does not go all the way.
Uses Tellud's Z-wave app.
Homey finds the plug and starts pairing, then after a few seconds the Android app says "that the plug is no longer contactable".
Although it continues to flash in pairing mode.

Is this Telldus Z-wave compatible?
What can cause the interruption in pair mode?

**Comment by yhaugom** [comment]
Hello.
Make sure to keep the plug close to Homey when pairing.
Yngve

Med vennlig hilsen
Yngve Bøe Haugom
Mobil: +47 996 96 088
________________________________
Fra: Ellwiz ***@***.***>
Sendt: Friday, December 3, 2021 9:43:24 AM
Til: yhaugom/com.telldus ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: [yhaugom/com.telldus] Unable to add Telldus TZWP-102/313510 (Issue #39)


Hello,
Want to leave my Animus Heart and just got my Homey Pro and started with connected a Telldus 433mhz plug without any problems.
When I´m trying add a Telldus Z-wave Miniplug TZWP-102/313510, pairing does not go all the way.
Uses Tellud's Z-wave app.
Homey finds the plug and starts pairing, then after a few seconds the Android app says "that the plug is no longer contactable".
Although it continues to flash in pairing mode.

Is this Telldus Z-wave compatible?
What can cause the interruption in pair mode?
