### ISSUE TITLE
Telldus Plug-in Switch Mini (313510)

### ISSUE THREAD

**Issue by nicleo** [yhaugom/com.telldus#40]
I have added 3 swithes and they work for a short while, then they stop responding. Even the physical button stops responding until I unplug/plug-in the switch. 
Any known issues?
V 1.2.1 on Homey Pro 7.2.1

**Comment by yhaugom** [comment]
Can you send me a bug report when this happens? Under App settings and diagnostics report.

**Comment by yhaugom** [comment]
I do not think this has anything to do with my code. Probably a range, interference or Homey issue. But I will have a look if you can send me the report.

**Comment by nicleo** [comment]
Done. 

ca65382b-0ead-4506-95c4-33d411a6359f

Mvh,
Nick Leo

———————————————
NICnet
Dalby Viggeby
SE-755 91 Uppsala
Sweden


sent from a device powered by 100% renewable energy
