### ISSUE TITLE
TZDW-100, The door/window sensor, battery reading

### ISSUE THREAD

**Issue by espenh1** [yhaugom/com.telldus#41]
Hi,

App works great. But, can you enable/fix/test battery reading? I saw your comment in the code "I do not think this device supports measure battery anyway", but when I did a google seach, I came across a comment in a homeseer thread that they made it work. 

Tnx

**Comment by yhaugom** [comment]
@espenh1 Do you have a reference to the Homeseer thread?

**Comment by espenh1** [comment]
@yhaugom - Hi, I am trying to find it again. How about this: https://github.com/openhab/org.openhab.binding.zwave/blob/main/doc/telldus/tzdw100_0_0.md

**Comment by espenh1** [comment]
I could be this one. It has references to the link in the other comment as well:  https://www.hjemmeautomasjon.no/forums/topic/2512-telldus-d%C3%B8rsensor/
I am hoping you can make it work in some way. Thanks :)

**Comment by yhaugom** [comment]
Published new version with meassure_battery to Homey app store. Not sure if the sensor reports accurate percentage between 1 and 100%, but I did test a couple of sensors before and after changing battery. They did update from 1% to 100%.
