### ISSUE TITLE
Plug, LED indicator setting

### ISSUE THREAD

**Issue by lurendrejer** [yhaugom/com.telldus#5]
The LED brightness indicator parameter doesn't work - when setting it via the app.

Setting the parameter RAW to 3,1,0 turns of the LED - selecting the value in the app does nothing.

**Comment by yhaugom** [comment]
Ok, then a parsing of the settings value is probably needed. Feel free to try it out. I am really busy these days.

**Comment by yhaugom** [comment]
@lurendrejer does this work better with newest version?

**Comment by lurendrejer** [comment]
Sorry, i am unable to test it.
I don't use Homey anymore.

**Comment by yhaugom** [comment]
3,1,0 for turning off the LED should now work in the app. I dont have the plug to test, but tested on the magnet switch where it works fine. Should be working here as well. I will close this issue.
