### ISSUE TITLE
Telldus plug in mini switch on/off with energy meter zwave is not workning, is not identified. please add it to the application

### ISSUE THREAD

**Issue by Artedi** [yhaugom/com.telldus#7]

**Comment by xeterixon** [comment]
I submitted a pull request for it today: [https://github.com/yhaugom/com.telldus/pull/6](https://github.com/yhaugom/com.telldus/pull/6).
Meanwhile you could use the code from my fork: [https://github.com/xeterixon/com.telldus](https://github.com/xeterixon/com.telldus)

**Comment by carlj0han** [comment]
+1 for mini switch support!

**Comment by yhaugom** [comment]
Thank you Xet Erixon!
I will try to submit this weekend.
Have had a look, and it looks good, so should be quick when I have the time.
Yngve

**Comment by yhaugom** [comment]
Submitted to appstore. Awaiting approval.

**Comment by yhaugom** [comment]
Published to the app store.
