### ISSUE TITLE
Problems w socket in flow

### ISSUE THREAD

**Issue by sauk1** [yhaugom/com.telldus#9]
Dont know if it is app related but I cant use the device command Turn on Lights Any zone. I need to add each socket in the flow with 1 sec delay to get everything to work.

**Comment by yhaugom** [comment]
This should be possible to set at inclusion time. When including a socket, you are supposed to be able to set a virtual class for what is plugged in. In the new app (soon to be released) you can change what is plugged in under device settings. When the category is set to Light, this should work.
